name: OpenWrt Builder

permissions: write-all

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      use_ccache:
        default: 'true'
        type: boolean
      openwrt_ip:
        default: '192.168.2.15'
        type: string
      ssh:
        default: 'false'
        type: boolean
  
env:
  REPO_URL: https://github.com/Lienol/openwrt
  REPO_BRANCH: "24.10"
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  DIY_P3_SH: diy-part3.sh
  TZ: Etc/UTC
  CCACHE_DIR: /builder/openwrt/.ccache

jobs:
  build:
    runs-on: ubuntu-24.04
    if: ${{ github.event.repository.owner.id == github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Initialize the build environment
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi -f $(docker images -q) 2>/dev/null || true
          [[ -n "${AGENT_TOOLSDIRECTORY}" ]] && sudo rm -rf "${AGENT_TOOLSDIRECTORY}"
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android 2>/dev/null
          sudo swapoff -a
          sudo rm -f /swapfile /mnt/swapfile
          sudo -E apt-get -y update
          sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby* || true
          sudo -E apt-get -y install $(curl -fsSL https://ophub.org/ubuntu2404-make-openwrt-depends)
          sudo -E systemctl daemon-reload
          #sudo -E apt-get -y full-upgrade
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          sudo sed -i '/NVM_DIR/d;/skel/d' /root/{.bashrc,.profile}
          sudo rm -rf ~/{.cargo,.dotnet,.rustup}
          sudo -E timedatectl set-timezone "${TZ:-Etc/UTC}"
          sudo -E ntpdate ntp.ubuntu.com 0.pool.ntp.org || true
          sudo -E timedatectl set-ntp true
          date -u
          timedatectl status || true
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Create virtual disk for extended storage
        run: |
          mnt_size=$(expr $(df -h /mnt | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 1)
          root_size=$(expr $(df -h / | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 4)
          sudo truncate -s "${mnt_size}"G /mnt/mnt.img
          sudo truncate -s "${root_size}"G /root.img
          sudo losetup /dev/loop6 /mnt/mnt.img
          sudo losetup /dev/loop7 /root.img
          sudo pvcreate /dev/loop6
          sudo pvcreate /dev/loop7
          sudo vgcreate github /dev/loop6 /dev/loop7
          sudo lvcreate -n runner -l 100%FREE github
          sudo mkfs.xfs -f -i sparse=0 -b size=4096 /dev/github/runner
          sudo mkdir -p /builder
          sudo mount /dev/github/runner /builder
          sudo chown -R runner:runner /builder
          df -Th
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Clone source code
        id: codes
        working-directory: /builder
        if: ${{ steps.init.outputs.status == 'success' && !cancelled() }}
        run: |
         # Determine the OpenWrt source code repository
         REPO_NAME="openwrt"
         # Clone the source code repository
          git clone -q --single-branch --depth=1 --branch=${REPO_BRANCH} ${REPO_URL} openwrt
          ln -sf /builder/openwrt ${{ github.workspace }}/openwrt
          ln -sf /builder/openwrt /home/runner/work/_actions/ophub/amlogic-s9xxx-openwrt/main/openwrt

          # Export build metadata
          echo "build_tag=${REPO_NAME}-${REPO_BRANCH}-$(date +"%Y.%m")" >> ${GITHUB_ENV}
          echo -e "REPO_URL: [ ${REPO_URL} ]\nREPO_BRANCH: [ ${REPO_BRANCH} ]\nREPO_NAME: [ ${REPO_NAME} ]"
          df -hT ${PWD}
          echo "REPO_URL=${REPO_URL}" >> ${GITHUB_ENV}
          echo "REPO_NAME=${REPO_NAME}" >> ${GITHUB_ENV}
          echo "REPO_BRANCH=${REPO_BRANCH}" >> ${GITHUB_ENV}
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Load custom feeds
        run: |
          chmod +x ${DIY_P1_SH}
          cd openwrt/
          ${{ github.workspace }}/${DIY_P1_SH}

      - name: Update feeds
        run: cd openwrt/ && ./scripts/feeds update -a

      - name: Install feeds
        run: cd openwrt/ && ./scripts/feeds install -a

      - name: Load custom configuration
        run: |
          [[ -e "${CONFIG_FILE}" ]] && cp -f ${CONFIG_FILE} openwrt/.config
          chmod +x ${DIY_P2_SH}
          chmod +x ${DIY_P3_SH}
          cd openwrt/
          ${{ github.workspace }}/${DIY_P2_SH}
          ${{ github.workspace }}/${DIY_P3_SH} "${{ inputs.openwrt_ip }}" "${{ inputs.use_ccache }}"

      - name: SSH connect to Actions
        uses: P3TERX/ssh2actions@main
        if: github.event.inputs.ssh == 'true'
      
      - name: Download package
        id: package
        run: |
          cd openwrt/
          make defconfig
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

      - name: Get OpenWrt source commit hash
        id: openwrthash
        run: |
          # Get the latest source hash from the kernel repository
          repo_path="$(echo "${{ env.REPO_URL }}" | awk -F"github.com/" '{print $2}')"
          api_url="https://api.github.com/repos/${repo_path}/git/ref/heads/${{ env.REPO_BRANCH }}"
          source_hash=$(curl -fsSL -m 20 \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              ${api_url} |
              jq -r '.object.sha'
          )
          [[ -z "${source_hash}" || "${source_hash}" == "null" ]] && source_hash="${{ github.sha }}"
          echo "source_hash=${source_hash}" >> ${GITHUB_ENV}
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Cache ccache
        uses: actions/cache@v5
        with:
          path: /builder/openwrt/.ccache
          key: ${{ env.REPO_NAME }}-${{ env.REPO_BRANCH }}-${{ env.source_hash }}
          restore-keys: |
            ${{ env.REPO_NAME }}-${{ env.REPO_BRANCH }}-

      - name: Compile the OpenWrt firmware
        id: compile
        run: |
          cd openwrt/
          echo -e "Compiling with $(nproc) threads"
          make -j$(($(nproc) + 1)) || make -j1 || make -j1 V=s

          echo -e "ccache statistics:"
          ccache -s 2>/dev/null
          echo -e "ccache directory size:"
          du -sh $(pwd)/.ccache 2>/dev/null || echo "No ccache directory found."

          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Clean up build files and reclaim disk space
        id: clean
        if: ${{ steps.compile.outputs.status == 'success' && !cancelled() }}
        run: |
          # Clean up build artifacts and reclaim disk space
          cd openwrt/
          [[ -d "output" ]] || mkdir output
          cp -f bin/targets/*/*/*rootfs.tar.gz output/
          cp -f .config output/config
          ls -A | grep -vE '^(output|\.ccache)$' | xargs rm -rf || true

          # Export build metadata
          df -hT ${PWD}
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Upload OpenWrt rootfs to Release
        uses: ncipollo/release-action@main
        if: ${{ steps.clean.outputs.status == 'success' && !cancelled() }}
        with:
          tag: ${{ env.build_tag }}
          artifacts: openwrt/output/*
          allowUpdates: true
          removeArtifacts: false
          replacesArtifacts: true
          makeLatest: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Package OpenWrt for target boards
        if: ${{ steps.clean.outputs.status == 'success' && !cancelled() }}
        uses: ophub/amlogic-s9xxx-openwrt@main
        with:
          openwrt_path: openwrt/output/*rootfs.tar.gz
          openwrt_ip: ${{ inputs.openwrt_ip }}
          openwrt_board: s905d
          openwrt_kernel: 6.12.y
          auto_kernel: true
          kernel_repo: ophub/kernel
          kernel_usage: stable
          builder_name: ophub

      - name: Backup ophub packaged firmware
        run: |
          mkdir -p upload_firmware
          cp -rf ${{ env.PACKAGED_OUTPUTPATH }}/* upload_firmware/
          rm -rf ${{ env.PACKAGED_OUTPUTPATH }}/*

      - name: Package OpenWrt Firmware
        uses: unifreq/openwrt_packit@master
        env:
          OPENWRT_ARMSR: openwrt/output/*rootfs.tar.gz
          PACKAGE_SOC: s905d
          KERNEL_REPO_URL: ophub/kernel
          KERNEL_VERSION_NAME: 6.12.y
          KERNEL_AUTO_LATEST: true
          OPENWRT_IP: ${{ inputs.openwrt_ip }}
          CUSTOMIZE_RK3399: none
          SCRIPT_DIY_PATH:
          WHOAMI: ophub

      - name: Merge unifreq packaged firmware
        run: |
          cp -rf ${{ env.PACKAGED_OUTPUTPATH }}/* upload_firmware/

      - name: Upload packaged OpenWrt to Release
        uses: ncipollo/release-action@main
        with:
          tag: ${{ env.build_tag }}
          artifacts: upload_firmware/*
          allowUpdates: true
          removeArtifacts: false
          replacesArtifacts: true
          makeLatest: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ### OpenWrt Image Information
            - Default IP: `${{ inputs.openwrt_ip }}`
            - Default username: `root`
            - Default password: `password`
            - Default WIFI name: `OpenWrt`
            - Default WIFI password: `none`
            ### Install to EMMC
            - Login to OpenWrt → `System` → `Amlogic Service` → `Install OpenWrt`
            ### OpenWrt source code
            - [${{ env.REPO_NAME }}](${{ env.REPO_URL }}/tree/${{ env.REPO_BRANCH }})
            ### Applicable Platform
            - 🐧 `arm64`
            - 🐋 Docker image: https://hub.docker.com/u/ophub
